create or replace function private.refresh_competition_formation_ranking_scope(target_season_id uuid,target_cycle_id uuid default null::uuid)
returns void language plpgsql security definer set search_path to '' as $$
begin
 delete from public.ranking_entries where ranking_type='doubles' and season_id=target_season_id and cycle_id is not distinct from target_cycle_id;
 delete from public.ranking_contributions where ranking_type='doubles' and season_id=target_season_id and cycle_id is not distinct from target_cycle_id;
 with tx_aggregate as (
  select rt.formation_id entity_id,sum(rt.points_applied)::integer total_points,sum(case when rt.rule_code in('WIN','LOSS') then rt.points_applied else 0 end)::integer result_points,sum(case when rt.rule_code in('ACE','ATTACK') then rt.points_applied else 0 end)::integer technical_points,sum(case when rt.rule_code='WIN' then case when rt.transaction_type='reversal' then -1 else 1 end else 0 end)::integer wins,sum(case when rt.rule_code='LOSS' then case when rt.transaction_type='reversal' then -1 else 1 end else 0 end)::integer losses,sum(case when rt.rule_code='ACE' then case when rt.transaction_type='reversal' then -1 else 1 end else 0 end)::integer aces,sum(case when rt.rule_code='ATTACK' then case when rt.transaction_type='reversal' then -1 else 1 end else 0 end)::integer attacks,max(rt.created_at) reached_score_at
  from public.ranking_transactions rt where rt.season_id=target_season_id and rt.status='homologated' and rt.transaction_scope='side' and rt.formation_id is not null and rt.season_cycle_id is not distinct from target_cycle_id and rt.rule_code in('WIN','LOSS','ACE','ATTACK') group by rt.formation_id having sum(rt.points_applied)<>0
 ),member_counts as (
  select formation_id,count(distinct athlete_id)::integer athletes_contributing from public.competition_formation_members group by formation_id
 ),aggregate_rows as (
  select cf.id entity_id,cf.display_name,cf.level,cf.team_id,t.name team_name,cf.pole_id,p.name pole_name,cc.code category_code,fmt.code format_code,tx.total_points,tx.result_points,tx.technical_points,tx.wins,tx.losses,tx.aces,tx.attacks,coalesce(mc.athletes_contributing,0)::integer athletes_contributing,tx.reached_score_at
  from tx_aggregate tx join public.competition_formations cf on cf.id=tx.entity_id join public.competitive_formats fmt on fmt.id=cf.format_id and fmt.code='doubles' left join public.competitive_categories cc on cc.id=cf.category_id left join public.teams t on t.id=cf.team_id left join public.poles p on p.id=cf.pole_id left join member_counts mc on mc.formation_id=cf.id where cf.season_id=target_season_id and cf.status='active'
 ),positioned as (
  select ar.*,case when(ar.wins+ar.losses)>0 then round(ar.wins::numeric*100/(ar.wins+ar.losses),4) else 0::numeric end calculated_win_rate,row_number() over(partition by ar.level order by ar.wins desc,case when(ar.wins+ar.losses)>0 then ar.wins::numeric/(ar.wins+ar.losses) else 0 end desc,ar.total_points desc,ar.aces desc,ar.attacks desc,ar.reached_score_at,ar.entity_id)::integer current_position,row_number() over(order by ar.wins desc,case when(ar.wins+ar.losses)>0 then ar.wins::numeric/(ar.wins+ar.losses) else 0 end desc,ar.total_points desc,ar.aces desc,ar.attacks desc,ar.reached_score_at,ar.entity_id)::integer general_position from aggregate_rows ar
 )
 insert into public.ranking_entries(ranking_type,season_id,cycle_id,entity_id,entity_code,display_name,level,team_id,team_name,pole_id,pole_name,category_code,format_code,total_points,participation_points,result_points,technical_points,bonus_points,penalty_points,disciplinary_balance,games_played,wins,losses,win_rate,aces,attacks,blocks,defenses,assists,athletes_contributing,teams_contributing,current_position,general_position,previous_position,position_change,movement,reached_score_at,refreshed_at)
 select 'doubles',target_season_id,target_cycle_id,p.entity_id,null,p.display_name,p.level,p.team_id,p.team_name,p.pole_id,p.pole_name,p.category_code,p.format_code,p.total_points,0,p.result_points,p.technical_points,0,0,0,p.wins+p.losses,p.wins,p.losses,p.calculated_win_rate,p.aces,p.attacks,0,0,0,p.athletes_contributing,case when p.team_id is null then 0 else 1 end,p.current_position,p.general_position,null,null,'new',p.reached_score_at,now() from positioned p;
end;$$;
