-- C29: W1–W13 is now the only supported season creation path.
-- Keep historical functions in place for migration compatibility, but remove
-- every externally usable EXECUTE grant from both public wrappers and private
-- implementations. The supported entry point is admin_create_quarter_season.

revoke all on function public.admin_create_season(
  text,
  text,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz
) from public, anon, authenticated, service_role;

revoke all on function private.admin_create_season(
  text,
  text,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz
) from public, anon, authenticated, service_role;

revoke all on function public.admin_create_season_cycle(
  uuid,
  smallint,
  text,
  timestamptz,
  timestamptz
) from public, anon, authenticated, service_role;

revoke all on function private.admin_create_season_cycle(
  uuid,
  smallint,
  text,
  timestamptz,
  timestamptz
) from public, anon, authenticated, service_role;

comment on function public.admin_create_season(
  text,
  text,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz,
  timestamptz
) is 'LEGACY / DISABLED: use public.admin_create_quarter_season(text,text,date).';

comment on function public.admin_create_season_cycle(
  uuid,
  smallint,
  text,
  timestamptz,
  timestamptz
) is 'LEGACY / DISABLED: compatibility cycles are generated by admin_create_quarter_season.';
